#include "shared/code_types.h"
#include "shared/code_visibility.h"
#include "shared/assertion.h"
#include "shared/memory_chunk.h"
#include "shared/collection_array.h"

#include "shared/math_scalar.h"
#include "shared/math_linear.h"
#include "shared/math_linear_i.h"
#include "shared/math_linear_extension.h"
#include "shared/math_bezier.h"
#include "shared/math_complex.h"
#include "shared/math_complex_i.h"
#include "shared/math_quaternion.h"
#include "shared/math_ray.h"

#include "shared/platform_api.h"

#include "demo/pathtracing/main.h"
// #include "demo/pacman/main.h"
// #include "demo/sound_test/main.h"
// #include "demo/conway_life/main.h"
// #include "demo/tetris/main.h"
// #include "demo/naive_silly_ecs/main.h"
// #include "demo/study_raytrace/main.h"
// #include "demo/study_raymarch/main.h"
